---
title: "Function documentation"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

 


# fct_read_lookup
    
```{r function-fct_read_lookup}
#' fct_read_lookup
#' 
#' Pull Data From ActivityInfo
#' 
#' Note that this function is specific to a specific DB schema -
#' the form to query as well as the columns variable name are hard coded and 
#' would need to be adjusted if the DB change
#' 
#' Note also that the function is based on a token stored as an environment 
#' variable
#' 
#'  # Credentials set up as environment variables - 
#'  
#'  # token <- "activityinfotoken.."
#'  # print(Sys.setenv(ACTIVITYINFOTOKEN = token))   
#'  # Sys.getenv("ACTIVITYINFOTOKEN")
#'  # rm(token)
#'  
#'  @param type of one 
#'                * dfadmin1  
#'                * dfadmin2  
#'                * dfindicator   
#'                * dfpartner  
#' 
#' @return frame with the content of the activity info DB 
#' 
#' 
#' @importFrom activityinfo activityInfoToken queryTable
#' @importFrom dplyr  arrange mutate_at rowwise ungroup
#' 
#' @export
fct_read_lookup <- function(type ){

  activityinfo::activityInfoToken(Sys.getenv("ACTIVITYINFOTOKEN"),
                                prompt = FALSE)

  # Not recommended but if needed, chose to write the 5W as a xlsx file in repository
  # Get other reference table used during the data quality check
  # Loaded from AI regardless the method for 5W used
  if( type == "admin1") {
  lookup  <- activityinfo::queryTable(
    form= "cryi2v5lo79a2dh9", #fix it 
                           "Country" = "c8u26b8kxeqpy0k4",
                           "Admin1" = "c3ns3zikxeqq4h95",
                           "ISOCode" = "cl3sspjkxeqq8yq6",
    truncateStrings = FALSE) |> 
    dplyr::rowwise() |> 
    dplyr::mutate(countryadmin1 = paste(Country, Admin1)) |> 
    dplyr::ungroup()
  }
  
  if( type == "admin2") {
  lookup <- activityinfo::queryTable(
    form= "cbxcifmlo79a2de3",  #fix it 
                         "Country" = "cnkb6jykxgdeemm4r.c8u26b8kxeqpy0k4",
                         "Admin1" = "cnkb6jykxgdeemm4r.c3ns3zikxeqq4h95",
                         "Admin2" = "cs2esadkx6hkt7j6", 
    truncateStrings = FALSE) |> 
    dplyr::rowwise() |> 
    dplyr::mutate(admin1and2 = paste(Admin1, Admin2)) |> 
    dplyr::ungroup()
  }
  
  if( type == "indicator") {
  lookup  <- activityinfo::queryTable(
    form= "cv2dgf6lo79a2de6",  #fix it 
                              "CODE" = "cdhugiblctco28h3",
                              "Subsector" = "cagw22hlctcp2vu5",
                              "Indicator" = "c1oo0eclctcqtjp8",
                              "IndicatorType" = "cuskmf7lctcszoga", 
    truncateStrings = FALSE) |> 
    dplyr::rowwise() |> 
    dplyr::mutate(sectindic = paste(Subsector, Indicator)) |> 
    dplyr::ungroup()
  }
  
  if( type == "partner") {
  lookup <- activityinfo::queryTable(
    form= "cwt6nqqlo79a2de7", #fix it
                          "AOIDORG" = "cnhvpo4kumvyqla8",
                          "Name" = "ckj5zamkumvyysv9",
                          "Type" = "c813krekumw0449j",
                          "RMlead" = "cu2zbr0l1z3adte7", 
                          truncateStrings = FALSE)
  
  }

   return(lookup)
    
}
```
  
```{r example-fct_read_lookup}
lookup_dfadmin1 <- fct_read_lookup(type = "admin1")
head(lookup_dfadmin1, 10)

lookup_dfadmin2 <- fct_read_lookup(type = "admin2")
head(lookup_dfadmin2, 10)

lookup_dfindicator <- fct_read_lookup(type = "indicator")
head(lookup_dfindicator, 10)

lookup_dfpartner <- fct_read_lookup(type = "partner")
head(lookup_dfpartner, 10)

```
  
```{r tests-fct_read_lookup}
test_that("fct_read_lookup works", {
  expect_true(inherits(fct_read_lookup, "function")) 
})
```  


# fct_read_data
    
```{r function-fct_read_data}
#' fct_read_data
#' 
#' Pull Data From ActivityInfo
#' 
#' Note that this function is specific to a specific DB schema -
#' the form to query as well as the columns variabl name are hard coded and 
#' would need to be adjusted if the DB change
#' 
#' Note also that the function is based on a token stored as an environment 
#' variable
#' 
#'  # Credentials set up as environment variables - 
#'  
#'  # token <- "activityinfotoken.."
#'  # print(Sys.setenv(ACTIVITYINFOTOKEN = token))   
#'  # Sys.getenv("ACTIVITYINFOTOKEN")
#'  # rm(token)
#'  
#' @param filter what to filter on (country or partner) so that we do not need to load everything
#' @param value value to filter from
#' 
#' @return  df5W  response tracking potentially filtered
#' 
#' 
#' @importFrom activityinfo activityInfoToken queryTable
#' @importFrom dplyr  arrange mutate_at rowwise ungroup
#' 
#' @export
fct_read_data <- function(filter = NULL ,
                          value = NULL){

  activityinfo::activityInfoToken(Sys.getenv("ACTIVITYINFOTOKEN"),
                                prompt = FALSE)

    # Get data from different sources
    if( all(!(is.null(filter)) & filter == "country") ) {
    df5W <-  activityinfo::queryTable(
      form ="cwp64n0lo79a2de8",
                        "Country" = "cezj1rqkxeqrsy57.c8u26b8kxeqpy0k4",
                        "Admin1" = "cezj1rqkxeqrsy57.c3ns3zikxeqq4h95",
                        "Admin2" = "c89klrbkx6hp4j58.cs2esadkx6hkt7j6",
                        "Appealing_org" = "c5648gjkx69ra2v9.ckj5zamkumvyysv9",
                        "Implementation" = "ckjtet4kx69smeog",
                        "Implementing_partner" = "cdocy6flctaah8c4.ckj5zamkumvyysv9",
                        "Month" = "clqgqrqkyueahma8",
                        "Subsector" = "cco8s7klctg5i192q.cagw22hlctcp2vu5",
                        "Indicator" = "cco8s7klctg5i192q.c1oo0eclctcqtjp8",
                        "Activity_Name" = "c3p669wkx6a7oyo4",
                        "Activity_Description" = "c8hxf50kx6a7vp65",
                        "RMRPActivity" = "cuf3og8kx6amylmf",
                        "CVA" = "cbvqg4jkx6b1kii7",
                        "Value" = "clwkfmckx6b2msu9",
                        "Delivery_mechanism" = "cg3rikqkx6b3z1kf",
                        "Quantity_output" = "cm6no26kx6b8fqoh",
                        "Total_monthly" = "cto1biukx6kwvnj4k",
                        "New_beneficiaries" = "c43j49ikx6kxyyc4l",
                        "IN_DESTINATION" = "cz3yof2kx6l024p4m",
                        "IN_TRANSIT" = "c8kl5o2kx6l0jip4n",
                        "Host_Communities" = "c5z8bvakx6l10d84o",
                        "PENDULARS" = "c72dmskkx6l1hl04p",
                        "Returnees" = "cmoqhuckx6l4q9z4q",
                        "Girls" = "cwrxeaekx6l63na4s",
                        "Boys" = "ccx7xhekx6l6jnk4t",
                        "Women" = "c3l36n2kx6l70kp4u",
                        "Men" = "ctd27ackx6l7g814v",
                        "Other_under" = "ckjcuiokx6l9a504w",
                        "Other_above" = "cq4hs3skx6lggpj4x",
                        "Platform" = "cuhb8obl0wjzz9r3",
       filter = sprintf('cezj1rqkxeqrsy57.c8u26b8kxeqpy0k4 == "%s" ', value),
       truncateStrings = FALSE)
      } else  if(  all(!(is.null(filter)) &  filter == "partner") ) {
       df5W <-  activityinfo::queryTable(
              form ="cwp64n0lo79a2de8",
                        "Country" = "cezj1rqkxeqrsy57.c8u26b8kxeqpy0k4",
                        "Admin1" = "cezj1rqkxeqrsy57.c3ns3zikxeqq4h95",
                        "Admin2" = "c89klrbkx6hp4j58.cs2esadkx6hkt7j6",
                        "Appealing_org" = "c5648gjkx69ra2v9.ckj5zamkumvyysv9",
                        "Implementation" = "ckjtet4kx69smeog",
                        "Implementing_partner" = "cdocy6flctaah8c4.ckj5zamkumvyysv9",
                        "Month" = "clqgqrqkyueahma8",
                        "Subsector" = "cco8s7klctg5i192q.cagw22hlctcp2vu5",
                        "Indicator" = "cco8s7klctg5i192q.c1oo0eclctcqtjp8",
                        "Activity_Name" = "c3p669wkx6a7oyo4",
                        "Activity_Description" = "c8hxf50kx6a7vp65",
                        "RMRPActivity" = "cuf3og8kx6amylmf",
                        "CVA" = "cbvqg4jkx6b1kii7",
                        "Value" = "clwkfmckx6b2msu9",
                        "Delivery_mechanism" = "cg3rikqkx6b3z1kf",
                        "Quantity_output" = "cm6no26kx6b8fqoh",
                        "Total_monthly" = "cto1biukx6kwvnj4k",
                        "New_beneficiaries" = "c43j49ikx6kxyyc4l",
                        "IN_DESTINATION" = "cz3yof2kx6l024p4m",
                        "IN_TRANSIT" = "c8kl5o2kx6l0jip4n",
                        "Host_Communities" = "c5z8bvakx6l10d84o",
                        "PENDULARS" = "c72dmskkx6l1hl04p",
                        "Returnees" = "cmoqhuckx6l4q9z4q",
                        "Girls" = "cwrxeaekx6l63na4s",
                        "Boys" = "ccx7xhekx6l6jnk4t",
                        "Women" = "c3l36n2kx6l70kp4u",
                        "Men" = "ctd27ackx6l7g814v",
                        "Other_under" = "ckjcuiokx6l9a504w",
                        "Other_above" = "cq4hs3skx6lggpj4x",
                        "Platform" = "cuhb8obl0wjzz9r3",
       filter = sprintf('c5648gjkx69ra2v9.ckj5zamkumvyysv9 == "%s" ', value),
       truncateStrings = FALSE)
      } else  {
      df5W <-  activityinfo::queryTable(
         form ="cwp64n0lo79a2de8",
                        "Country" = "cezj1rqkxeqrsy57.c8u26b8kxeqpy0k4",
                        "Admin1" = "cezj1rqkxeqrsy57.c3ns3zikxeqq4h95",
                        "Admin2" = "c89klrbkx6hp4j58.cs2esadkx6hkt7j6",
                        "Appealing_org" = "c5648gjkx69ra2v9.ckj5zamkumvyysv9",
                        "Implementation" = "ckjtet4kx69smeog",
                        "Implementing_partner" = "cdocy6flctaah8c4.ckj5zamkumvyysv9",
                        "Month" = "clqgqrqkyueahma8",
                        "Subsector" = "cco8s7klctg5i192q.cagw22hlctcp2vu5",
                        "Indicator" = "cco8s7klctg5i192q.c1oo0eclctcqtjp8",
                        "Activity_Name" = "c3p669wkx6a7oyo4",
                        "Activity_Description" = "c8hxf50kx6a7vp65",
                        "RMRPActivity" = "cuf3og8kx6amylmf",
                        "CVA" = "cbvqg4jkx6b1kii7",
                        "Value" = "clwkfmckx6b2msu9",
                        "Delivery_mechanism" = "cg3rikqkx6b3z1kf",
                        "Quantity_output" = "cm6no26kx6b8fqoh",
                        "Total_monthly" = "cto1biukx6kwvnj4k",
                        "New_beneficiaries" = "c43j49ikx6kxyyc4l",
                        "IN_DESTINATION" = "cz3yof2kx6l024p4m",
                        "IN_TRANSIT" = "c8kl5o2kx6l0jip4n",
                        "Host_Communities" = "c5z8bvakx6l10d84o",
                        "PENDULARS" = "c72dmskkx6l1hl04p",
                        "Returnees" = "cmoqhuckx6l4q9z4q",
                        "Girls" = "cwrxeaekx6l63na4s",
                        "Boys" = "ccx7xhekx6l6jnk4t",
                        "Women" = "c3l36n2kx6l70kp4u",
                        "Men" = "ctd27ackx6l7g814v",
                        "Other_under" = "ckjcuiokx6l9a504w",
                        "Other_above" = "cq4hs3skx6lggpj4x",
                        "Platform" = "cuhb8obl0wjzz9r3",
      truncateStrings = FALSE)
      }
  
  # Short data wrangling for integer values
  df5W <- df5W |>
    dplyr::mutate_at(c("Value",
                "Quantity_output",
                "Total_monthly",
                "New_beneficiaries",
                "IN_DESTINATION",
                "IN_TRANSIT",
                "Host_Communities",
                "PENDULARS",
                "Returnees",
                "Girls",
                "Boys",
                "Women",
                "Men",
                "Other_under",
                "Other_above"), as.numeric) |>
    dplyr::arrange(Country, Month)

   return(df5W)
}
```
  
```{r example-fct_read_data}

## Pulling everything... can be long..
df5W <- fct_read_data()
head( df5W, 10)

## testing the filters
df5Wctr <- fct_read_data(filter = "country",
                         value = "Colombia")
head( df5Wctr, 10)

df5Wpart <- fct_read_data(filter = "partner",
                         value = "United Nations High Commissioner for Refugees (UNHCR)")
head( df5Wpart , 10)

df5Wpart2 <- fct_read_data(filter = "partner",
                         value = "CCEFIRO Association")

```
  
```{r tests-fct_read_data}
test_that("fct_read_data works", {
  expect_true(inherits(fct_read_data, "function")) 
})
```



# fct_error_report
    
```{r function-fct_error_report}
#' fct_error_report
#' 
#' The functions perform systematic Data Quality Check 
#' 
#' Currently this includes the 19 following Check: 
#' 
#'  __Completeness__:
#' 
#'  1. missingcountry: Country and admin 1 information is missing.
#'  2. countryadmincheck: Administrative unit level 1 not matching the name in the ActivityInfo 5W "admin2" reference table.
#'  3.  admin1and2check: Administrative unit level 2 not matching the name for each respective admin1 in the ActivityInfo 5W "admin2" reference table. 
#'  4.  miss_appeal_org: Missing appealing organization or organization name not corresponding to the name included in the ActivityInfo 5W "partners" reference table
#'  5.  miss_setup: Checks if the field is empty, as it is mandatory to fill this variable with a "yes" for cases where there is an implementing partner, or with a "no" if the activity corresponds to direct implementation.
#'  6.  miss_implementing_org: If "yes" is selected in the "implementation set up" field, then a name for the implementing organization should be included in the corresponding field, otherwise it will retrieve an error.
#'  7.  miss_month: Missing month information.
#'  8.  missing_what: If there is missing information for the 5W "what" fields, more specifically: indicator sector, indicator, activity name, RMRP activity, and CVA.
#'   
#'  __Consistency__:
#'  9.  wrongsectindicator: If the indicator name does not correspond to the selected sector, as per the ActivityInfo 5W "indicators RMRP 23" reference table. 
#'  10.  zeroCVA: when the CVA field is "yes", then a CVA value in USD must be entered, otherwise it will retrieve an error.
#'  11.  missingmechanism: when the CVA field is "yes", then a CVA delivery mechanism must be entered, otherwise it will retrieve an error.
#'  12.  CVANotoYes: If the CVA = “No” but that the Value or Delivery Mechanism contains data, it will retrieve an error as those should be empty or the CVA should be “Yes”.          
#'  13.  MultipurposeSector: It will retrieve an error when the selected indicator sector is "Multipurpose Cash Assistance (MPC)" and CVA = "No". 
#'  14.  DirectAssistanceNoBenef: If the indicator type selected is "Direct Assistance" then there should be positive values entered for new monthly beneficiaries and total beneficiaries, otherwise it will retrieve an error.  
#'  15.  NewBenefvstotal: if the value for new monthly beneficiaries exceeds the value of total monthly beneficiaries. 
#'  
#'  __Accuracy__:
#'  16.  PopTypeBreakdown:  For "Direct Assistance" indicators, checks if the sum of the population type breakdown equals the new beneficiaries value. If an ERROR appears, please review the breakdown values or the new beneficiaries' values in the corresponding activity
#'  17.  AGDBreakdown: For "Direct Assistance" indicators, checks if the sum of the age and gender breakdown equals the new beneficiaries' value. If an ERROR appears, please review the breakdown values or the new beneficiaries' values in the corresponding activity
#'  18.  CBuildingNoBenef: For "Capacity Building" indicators, checks if there is positive values for the total monthly beneficiaries field, as this field should be reported, otherwise it will retrieve an error.
#'  19.  NoOutput: For indicators other than the ones included under "Direct Assistance" and "Capacity Building", a value for"Quantity of Output" should always be reported, otherwise it will retrieve an error.
#' 
#' 
#' @param df5W fame with response tracking data
#' @param lookup_dfindicator fame with indicator look up 
#' @param lookup_dfadmin1 fame with admin1 look up 
#' @param lookup_dfadmin2 fame with admin2 look up 
#' @param lookup_dfpartner fame with partner look up 
#' 
#' @import ggplot2 
#' @importFrom scales label_number cut_short_scale
#' @importFrom unhcrthemes theme_unhcr
#' @importFrom dplyr arrange mutate  left_join select ungroup 
#'                    rowwise row_number
#'                    
#' @importFrom purrr discard
#' 
#' @return result list with results and data error...
#' 
#' @export
fct_error_report <- function(df5W, 
                             lookup_dfadmin1, 
                             lookup_dfadmin2, 
                             lookup_dfindicator, 
                             lookup_dfpartner ){
  
  colnames(df5W) <- c("Country",
                 "Admin1",
                 "Admin2",
                 "Appealing_org",
                 "Implementation",
                 "Implementing_partner",
                 "Month",
                 "Subsector",
                 "Indicator",
                 "Activity_Name",
                 "Activity_Description",
                 "RMRPActivity",
                 "CVA",
                 "Value",
                 "Delivery_mechanism",
                 "Quantity_output",
                 "Total_monthly",
                 "New_beneficiaries",
                 "IN_DESTINATION",
                 "IN_TRANSIT",
                 "Host_Communities",
                 "PENDULARS",
                 "Returnees",
                 "Girls",
                 "Boys",
                 "Women",
                 "Men",
                 "Other_under",
                 "Other_above",
                 "Platform")
  
  
  df5W <- df5W |> 
    dplyr::select(1:30)
  
  
  # Data wrangling of reference table for quality check
  # Vectors for verification
  partnerlist <- unique(as.vector(lookup_dfpartner["Name"]))
  countrylist <- unique(as.vector(lookup_dfadmin1["countryadmin1"]))
  admin2list <- unique(as.vector(lookup_dfadmin2["admin1and2"]))
  sectindiclist <-  as.vector(lookup_dfindicator["sectindic"])
  
  # concatenate relevant columns to then check if cascading values are matching, 
  df5Werror <- df5W  |>
    dplyr::mutate(
      countryadmin1 = paste(Country, Admin1),
      Admin1and2 = paste(Admin1, Admin2),
      sectorindicator = paste(Subsector, Indicator)) |>
    dplyr::left_join(lookup_dfindicator, by = c("Subsector", "Indicator")) |>
    dplyr::select(-CODE, -sectindic)
    
  # Data Quality Check #############
  df5Werror <- df5Werror  |>
    dplyr::rowwise() |>
    # Where: check missing mandatory fields, 
    # Country-Admin1 pairs and Admin1-Admin2 pairs
    dplyr::mutate(
      missingcountry = ifelse(is.na(Country) | is.na(Admin1), 1,  NA),
      countryadmincheck = ifelse(!any(countryadmin1 == countrylist[[1]]), 1,  NA),
      admin1and2check = ifelse(!is.na(Admin2) & !any(Admin1and2 == admin2list[[1]]), 1,  NA),
    # Who: Missing values and Org names that are not part of the list
      miss_appeal_org = ifelse(!is.na(Appealing_org) & any(Appealing_org == partnerlist[[1]]),  NA, 1),
      miss_setup = ifelse(is.na(Implementation), 1,  NA),
      miss_implementing_org = ifelse((Implementation == "Yes" & 
                                        (is.na(Implementing_partner) | !any(Implementing_partner == partnerlist[[1]]))) | 
                                       (Implementation == "No" & !is.na(Implementing_partner)), 1,  NA),
      # When: Missing month
      miss_month = ifelse(is.na(Month), 1,  NA),
      # What: missing values and inconsistencies in CVA
      missing_what = ifelse(is.na(Subsector)|is.na(Indicator)|is.na(Activity_Name)| is.na(RMRPActivity)|is.na(CVA), 1,  NA),
      wrongsectindicator = ifelse(!any(sectorindicator == sectindiclist[[1]]), 1,  NA),
      # CVA mistakes
      zeroCVA = ifelse(CVA == "Yes" & (is.na(Value)|  Value == 0), 1,  NA),
      missingmechanism = ifelse(CVA == "Yes" & is.na(Delivery_mechanism), 1,  NA),
      CVANotoYes = ifelse((!is.na(Delivery_mechanism) | (!is.na(Value) & Value > 0)) & CVA == "No", 1,  NA),
      MultipurposeSector = ifelse(Subsector == "Multipurpose Cash Assistance (MPC)" & CVA == "No", 1,  NA),
      # Output and Breakdown related mistakes. Reviews will be divided according to indicator types
      # PNiN indicator related mistakes
      DirectAssistanceNoBenef = ifelse(IndicatorType == 'Direct Assistance' &
                                         ((is.na(New_beneficiaries) | New_beneficiaries == 0) &
                                            (is.na(Total_monthly) | Total_monthly == 0)), 1,  NA),
      NewBenefvstotal = ifelse(IndicatorType == 'Direct Assistance' & New_beneficiaries > Total_monthly, 1,  NA),
      PopTypeBreakdown = ifelse(IndicatorType == 'Direct Assistance' & New_beneficiaries != sum(IN_DESTINATION,
                                                                                   IN_TRANSIT,
                                                                                   Host_Communities,
                                                                                   PENDULARS,
                                                                                   Returnees, na.rm = TRUE), 1,  NA),
      AGDBreakdown = ifelse(IndicatorType == 'Direct Assistance' & New_beneficiaries != sum(Girls,
                                                                                Boys,
                                                                                Women,
                                                                                Men,
                                                                              Other_under,
                                                                                Other_above, na.rm = TRUE), 1,  NA),
      # Capacity Building indicators
      CBuildingNoBenef = ifelse(IndicatorType == 'Capacity Building' &
                                  (Total_monthly == 0 | is.na(Total_monthly)),
                                1,  NA),
      # Todos los otros indicadores
      NoOutput = ifelse ((IndicatorType != 'Capacity Building' &
                            IndicatorType != 'Direct Assistance') & 
                           (Quantity_output == 0 | is.na(Quantity_output)), 
                         1,  NA)   ) |>
    ## Compile all errors 
    dplyr::mutate( QA = sum( 
      c( missingcountry, countryadmincheck, admin1and2check, miss_appeal_org,
         miss_setup, miss_implementing_org, miss_month, missing_what, 
         wrongsectindicator, zeroCVA, missingmechanism, CVANotoYes,
         MultipurposeSector, DirectAssistanceNoBenef, NewBenefvstotal, 
         PopTypeBreakdown, AGDBreakdown, CBuildingNoBenef, NoOutput) , 
      na.rm = TRUE))|> 
    dplyr::ungroup() |> 
    ## Remove empty column
    purrr::discard(~all(is.na(.) | . =="")) |> 
    dplyr::mutate(Review = ifelse(QA > 0, "Please review activity", "OK"),
                  Review2 = ifelse(QA > 0, 1, NA))
  
   # table( df5Werror$QA, useNA = "ifany")
   # table( df5Werror$Review, useNA = "ifany")
   #table( df5Werror$Review2, useNA = "ifany")
   ## Add to result
  
 
  ## Add summary plot 
   
   
  # df5Werror |> 
  #   dplyr::select(Appealing_org, Review ) |>
  #   dply::group_by(Appealing_org) |>
  #   dplyr::summarise(Review = dplyr:: )
  # pivot_longer(cols = -Year) |>
  # ggplot() +
  # geom_col(aes(x = Year, y = value, fill = name),
  #          width = 0.7,
  #          position = position_fill()) +
  # unhcrthemes::scale_fill_unhcr_d(palette = "pal_unhcr") +
  # scale_y_continuous(expand = expansion(c(0, 0.01)),
  #                    labels = percent) +
  # labs(title = "Levels of earmarking | 2012-2020",
  #      caption = paste0( "Source:R4V | Data as of ",format(Sys.Date(),  '%d %B %Y'))   ) +
  # unhcrthemes::theme_unhcr(font_size = 14,
  #             grid = "Y",
  #             axis = "x",
  #             axis_title = FALSE)
   
   require(ggplot2)
  plot_Appealing <- df5Werror |>
        dplyr::select(Appealing_org, Review2 ) |>
        dplyr::group_by(Appealing_org) |>
        dplyr::summarise(Review2 = sum(Review2, na.rm = TRUE) ) |>
       dplyr::filter(Review2  >0 )|>
	      #filter(!is.na(Review)) |>
	      ggplot2::ggplot() +
	      aes(x = reorder(Appealing_org, Review2),
	          y = Review2) +
	      geom_col(fill = "#0c4c8a" ) +
       # scale_y_continuous(expand = expansion(c(0, 0.1)),
       #               labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
	      coord_flip()  +
        labs(
            title =  "Number of Activity to review by Appealing Org.",
            subtitle = "Data Quality Review",
            x = "",
            y = "",
            caption = paste0( "Source:R4V | Data as of ",format(Sys.Date(),  '%d %B %Y'))    ) +
        unhcrthemes::theme_unhcr(font_size = 14,
                      grid = "X"#,
                      #rel_small = 6/9#,
                     # axis = "y",
                      #axis_title = TRUE,
                     # legend = FALSE,
                     # axis_text = "y"
                    )
  
  
   ## Second plot 
  plot_Country <-  df5Werror |>
        dplyr::select(Country, Review2 ) |>
        dplyr::group_by(Country) |>
        dplyr::summarise(Review2 = sum(Review2, na.rm = TRUE) ) |>
       dplyr::filter(Review2  >0 )|>
	      ggplot() +
	      aes(x =  reorder(Country, Review2) , 
	          y = Review2) +
	      geom_col(fill = "#0c4c8a") +
       # scale_y_continuous(expand = expansion(c(0, 0.1)),
       #               labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
	      coord_flip()  +
        labs(
            title =  "Number of Activity to review by Country",
            subtitle = "Data Quality Review",
            x = "",
            y = "",
            caption = paste0( "Source: R4V | Data as of ",
             format(Sys.Date(),  '%d %B %Y'))    ) +
        unhcrthemes::theme_unhcr(font_size = 14,
                      grid = "X"#,
                      #rel_small = 6/9#,
                     # axis = "y",
                      #axis_title = TRUE,
                     # legend = FALSE,
                     # axis_text = "y"
                    )
   result <- list (
               ErrorReportclean = df5Werror, 
               plot_Country = plot_Country,
               plot_Appealing = plot_Appealing)

  return(result)
    
}
```
  
```{r example-fct_error_report}
lookup_dfadmin1 <- fct_read_lookup(type = "admin1")
lookup_dfadmin2 <- fct_read_lookup(type = "admin2")
lookup_dfpartner <- fct_read_lookup(type = "partner")
lookup_dfindicator <- fct_read_lookup(type = "indicator")

## First example
df5Wpart <- fct_read_data(filter = "partner",
    value = "United Nations High Commissioner for Refugees (UNHCR)")
resultpart <- fct_error_report(df5Wpart, 
                               lookup_dfadmin1, 
                               lookup_dfadmin2, 
                               lookup_dfindicator, 
                               lookup_dfpartner)
 
print(resultpart$plot_Country)

## Second example
df5Wctr <- fct_read_data(filter = "country",
                         value = "Peru")
resultctr <- fct_error_report(df5Wctr, 
                               lookup_dfadmin1, 
                               lookup_dfadmin2, 
                               lookup_dfindicator, 
                               lookup_dfpartner)

print(resultctr$plot_Appealing) 
head(resultctr[["ErrorReportclean"]], 10)


## last example with offline data..
df5Woffline <-  readxl::read_excel( system.file("Activities_5W_2024.xlsx", 
                                                package = "ActivtityInfoQuality") )
resultctr <- fct_error_report(df5Woffline, 
                               lookup_dfadmin1, 
                               lookup_dfadmin2, 
                               lookup_dfindicator, 
                               lookup_dfpartner)


```
  
```{r tests-fct_error_report}
test_that("fct_error_report works", {
  expect_true(inherits(fct_error_report, "function")) 
})
```

# fct_aggregate_data
    
```{r function-fct_aggregate_data}
#' fct_aggregate_data
#' 
#' Function to aggregate data according to different scenario
#' 
#' @param df5W fame with response tracking data
#' @param lookup_dfindicator fame with indicator look up 
#' @param proportions  can be "pin" or "target" - this uses configuration available 
#'                      within the spreadsheet inst/Proportions.xlsx
#' @param totalmodel   can be either: 
#'                     *  "sum":  sums all beneficiaries of all sectors to get
#'                      intersector figures per admin1 level and then at national level
#'                     
#'                     *  "maxsector" : sums all beneficiaries at sector and admin1
#'                       level, then take the max of each age and gender categories
#'                        for each population type to get the intersector figure 
#'                      
#'                     *  "southernconemodel" : Mixed approach in 3 steps: 
#'                     
#'                     1. Max across Shelter, Food security, Humanitarian transport
#'                         and WASH 
#'                         
#'                     2. Take Protection (General) data  
#'                     
#'                     3.  Sum Other sectors mentionned: Integration, 
#'                         Multipurporse CBI, Health, Education
#'                     
#'                     
#' @importFrom dplyr arrange mutate mutate_if left_join select ungroup 
#'                    rowwise row_number group_by summarise full_join
#'                    across where semi_join
#' @importFrom tibble as_tibble 
#' @importFrom tidyr replace_na                   
#' @return list with results
#' 
#' @export
fct_aggregate_data <- function(df5W,
                               lookup_dfindicator,
                             proportions = "pin", 
                             totalmodel = "sum"){
  
  colnames(df5W) <- c("Country",
                 "Admin1",
                 "Admin2",
                 "Appealing_org",
                 "Implementation",
                 "Implementing_partner",
                 "Month",
                 "Subsector",
                 "Indicator",
                 "Activity_Name",
                 "Activity_Description",
                 "RMRPActivity",
                 "CVA",
                 "Value",
                 "Delivery_mechanism",
                 "Quantity_output",
                 "Total_monthly",
                 "New_beneficiaries",
                 "IN_DESTINATION",
                 "IN_TRANSIT",
                 "Host_Communities",
                 "PENDULARS",
                 "Returnees",
                 "Girls",
                 "Boys",
                 "Women",
                 "Men",
                 "Other_under",
                 "Other_above",
                 "Platform")
  
  df5W <- df5W |> 
    dplyr::select(1:30)
  
  # Filter by the needed country and PiN indicators only

  df5Wconsolidated <- df5W  |>  
      dplyr::left_join(lookup_dfindicator, by = c("Subsector", "Indicator")) |> 
      dplyr::select(-CODE, -sectindic) |> 
      dplyr::filter(IndicatorType == "Direct Assistance") |> 
      dplyr::mutate_if(is.numeric, 
                       tidyr::replace_na, 
                        replace = 0)  
 
 
  # Create a vector based on Activity's months to the filter the template
    monthlist <- tibble::as_tibble(unique(df5Wconsolidated["Month"]))
    
  # Get consolidated template file
  #dftemplate <- readxl::read_excel("data/Consolidated_Template.xlsx")
  dftemplate <- readxl::read_excel( system.file("Consolidated_Template.xlsx", 
                                                package = "ActivtityInfoQuality") )



    dftemplate <- dftemplate |> 
      dplyr::semi_join(monthlist, by = "Month")

    # Get proportions file for each sector in Admin1 and poptype categories
    if (proportions == "pin")  {
      dfproportions <- readxl::read_excel(
         system.file("Proportions.xlsx", 
                     package = "ActivtityInfoQuality"), 
         sheet = "pinproportions")
    } else if (proportions == "target") {
      dfproportions <- readxl::read_excel(
         system.file("Proportions.xlsx", 
                     package = "ActivtityInfoQuality"), 
          sheet = "targetproportions")
    }


#################### 1. Total Monthly figures ###########

# Get monthly total figures of persons per Admin1 per sector
# sum Total beneficiaries of every activities 

monthlysectors <- df5Wconsolidated |> 
  dplyr::group_by(Country, Admin1, Month, Subsector) |> 
  dplyr::summarise('Monthly Total Beneficiaries' = sum(Total_monthly))

monthlytotal <- monthlysectors |> 
  dplyr::group_by(Country, Admin1, Month) |> 
  dplyr::summarise(Subsector = "Intersector", 
            'Monthly Total Beneficiaries' = sum(`Monthly Total Beneficiaries`))

monthly<- rbind(monthlysectors, monthlytotal)

# Get CVA Beneficiaries monthly total figures of persons per Admin1 per sector
# sum Total beneficiaries of every activities 

CVAmonthlysectors <- df5Wconsolidated |> 
  dplyr::filter(CVA == 'Yes') |> 
  dplyr::group_by(Country, Admin1, Month, Subsector) |> 
  dplyr::summarise('Monthly CVA Beneficiaries' = sum(Total_monthly))

CVAmonthlytotal <- CVAmonthlysectors |> 
  dplyr::group_by(Country, Admin1, Month) |> 
  dplyr::summarise(Subsector = "Intersector", 
            'Monthly CVA Beneficiaries' = sum(`Monthly CVA Beneficiaries`))

CVAmonthly<- rbind(CVAmonthlysectors, CVAmonthlytotal)

finalmonthlyadm1 <- monthly |> 
  dplyr::full_join(CVAmonthly, by = c("Country", "Admin1", "Month", "Subsector")) |> 
  dplyr::mutate(  dplyr::across( dplyr::where(is.numeric),
                tidyr::replace_na, 0))

# Get country level data

finalmonthcountry <- finalmonthlyadm1  |> 
  dplyr::group_by(Country, Month, Subsector) |> 
  dplyr::summarise(Admin1 = "Country level",
            'Monthly Total Beneficiaries' = sum(`Monthly Total Beneficiaries`),
            'Monthly CVA Beneficiaries' = sum(`Monthly CVA Beneficiaries`))

finalmonthlytotal <- rbind(finalmonthlyadm1, finalmonthcountry)

#################### 2. Consolidated figures ##############################

###### 2.1 Sector level ################
# Figures at sector and admin1 level are solely calculated through a sum
# If required by some platform, we can develop a indicator based system tailored for countries.

conssectors <-  df5Wconsolidated |> 
  dplyr::group_by(Country, Admin1, Month, Subsector) |> 
  dplyr::summarise(Monthly_Consolidated = sum(New_beneficiaries),
            Consolidated_RMindestination = sum(IN_DESTINATION), 
            Consolidated_RM_in_transit = sum(IN_TRANSIT),
            Consolidated_Host_Community = sum(Host_Communities),
            Consolidated_RM_Pendulars = sum(PENDULARS),
            Consolidated_Colombian_Returnees = sum(Returnees),
            Consolidated_Girls = sum(Girls), 
            Consolidated_Boys = sum(Boys),
            Consolidated_Women = sum(Women),
            Consolidated_Men = sum(Men),
            Consolidated_Other_under_18 = sum(Other_under),
            Consolidated_Other_above_18 = sum(Other_above)
  )

consCVAsectors <- df5Wconsolidated |> 
  dplyr::filter(CVA == "Yes") |> 
  dplyr::group_by(Country, Admin1, Month, Subsector) |> 
  dplyr::summarise(Consolidated_CVA_Beneficiaries = sum(New_beneficiaries))

consallsectors <- conssectors |> 
  dplyr::full_join(consCVAsectors, by = c("Country", "Admin1", "Month", "Subsector")) |> 
  dplyr::mutate(dplyr::across( dplyr::where(is.numeric),
                   tidyr::replace_na, 0))

###### 2.2 Intersector level ################
# Chose the consoldated model you want to use (see "Consolidated guidance" document 
# in GitHub repository)


# Model 1: Sum All: sums all beneficiaries of all sectors to get intersector figures
# per admin1 level and then at national level
if (totalmodel == "sum")
{
  conssumadm1 <- consallsectors |> 
  dplyr::group_by(Country, Admin1, Month) |> 
  dplyr::summarise(Subsector = "Intersector",
            Monthly_Consolidated = sum(Monthly_Consolidated),
            Consolidated_RMindestination = sum( Consolidated_RMindestination), 
            Consolidated_RM_in_transit = sum(Consolidated_RM_in_transit),
            Consolidated_Host_Community = sum(Consolidated_Host_Community),
            Consolidated_RM_Pendulars = sum(Consolidated_RM_Pendulars),
            Consolidated_Colombian_Returnees = sum(Consolidated_Colombian_Returnees),
            Consolidated_Girls = sum(Consolidated_Girls), 
            Consolidated_Boys = sum(Consolidated_Boys),
            Consolidated_Women = sum( Consolidated_Women),
            Consolidated_Men = sum(Consolidated_Men),
            Consolidated_Other_under_18 = sum(Consolidated_Other_under_18),
            Consolidated_Other_above_18 = sum(Consolidated_Other_above_18),
            Consolidated_CVA_Beneficiaries = sum(Consolidated_CVA_Beneficiaries)
            )
# Join Admin1-Intersector table to Admin1-Sector table
consfinaladmin1 <- rbind(consallsectors, conssumadm1)

# Sum Admin1 figures for sector and intersector to get the full final table
consfinalcountrylevel <- consfinaladmin1  |> 
  dplyr::group_by(Country, Month, Subsector) |> 
  dplyr::summarise(Admin1 = "Country level",
            Monthly_Consolidated = sum(Monthly_Consolidated),
            Consolidated_RMindestination = sum( Consolidated_RMindestination), 
            Consolidated_RM_in_transit = sum(Consolidated_RM_in_transit),
            Consolidated_Host_Community = sum(Consolidated_Host_Community),
            Consolidated_RM_Pendulars = sum(Consolidated_RM_Pendulars),
            Consolidated_Colombian_Returnees = sum(Consolidated_Colombian_Returnees),
            Consolidated_Girls = sum(Consolidated_Girls), 
            Consolidated_Boys = sum(Consolidated_Boys),
            Consolidated_Women = sum( Consolidated_Women),
            Consolidated_Men = sum(Consolidated_Men),
            Consolidated_Other_under_18 = sum(Consolidated_Other_under_18),
            Consolidated_Other_above_18 = sum(Consolidated_Other_above_18),
            Consolidated_CVA_Beneficiaries = sum(Consolidated_CVA_Beneficiaries)
  )

consfinal <- rbind(consfinaladmin1, consfinalcountrylevel) |> 
  dplyr::arrange(Country, Admin1)
}

if (totalmodel == "maxsector")
  { 
  # Model 2: Max Sector: sums all beneficiaries at sector and admin1 level, then take
  # the max of each age and gender categories for each population type to get the intersector figure
  
  consmaxmerge <- consallsectors |> 
  dplyr::left_join(dfproportions, by = c("Country", "Admin1", "Subsector")) |> 
  # Drop AGD Categories as they will be substituted in the final file
  dplyr::select(-Consolidated_Girls, 
         -Consolidated_Boys, 
         -Consolidated_Women, 
         -Consolidated_Men, 
         -Consolidated_Other_above_18, 
         -Consolidated_Other_under_18) |> 
  # get the breakdown of each age and gender categories by multiplying the pop type category by the proportions
  dplyr::rowwise() |> 
  dplyr::mutate(RMDestGirls = round(Consolidated_RMindestination * Dest_GIrls,0),
         RMDestBoys = round(Consolidated_RMindestination * Dest_Boys,0),
         RMDestWomen = round(Consolidated_RMindestination * Dest_Women,0),
         RMDestMen = round(Consolidated_RMindestination * Dest_Men,0),
         RMTransitGirls = round(Consolidated_RM_in_transit * Transit_GIrls,0),
         RMTransitBoys = round(Consolidated_RM_in_transit * Transit_Boys,0),
         RMTransitWomen = round(Consolidated_RM_in_transit * Transit_Women,0),
         RMTransitMen = round(Consolidated_RM_in_transit * Transit_Men,0),
         RMHCGirls = round(Consolidated_Host_Community * HC_Girls,0),
         RMHCBoys = round(Consolidated_Host_Community * HC_Boys,0),
         RMHCWomen = round(Consolidated_Host_Community * HC_Women,0),
         RMHCMen = round(Consolidated_Host_Community * HC_Men,0),
         RMPendularGirls = round(Consolidated_RM_Pendulars * Pendular_Girls,0),
         RMPendularBoys = round(Consolidated_RM_Pendulars * Pendular_Boys,0),
         RMPendularWomen = round(Consolidated_RM_Pendulars * Pendular_Women,0),
         RMPendularMen = round(Consolidated_RM_Pendulars * Pendular_Men,0),
         RMReturneesGirls = round(Consolidated_Colombian_Returnees*Returnees_Girls,0),
         RMReturneesBoys = round(Consolidated_Colombian_Returnees*Returnees_Boys,0),
         RMReturneesWomen = round(Consolidated_Colombian_Returnees*Returnees_Women,0),
         RMReturneesMen = round(Consolidated_Colombian_Returnees*Returnees_Men,0)) |> 
  dplyr::ungroup() |> 
  dplyr::select(-(5:10),-(12:35)) |> 
  dplyr::group_by(Country, Admin1, Month) |> 
  # Get MAX Values for each Age and Gender categories in each population type
  dplyr::summarise(Subsector = "Intersector",
            RMDestGirls = max(RMDestGirls),
            RMDestBoys = max(RMDestBoys),
            RMDestWomen = max(RMDestWomen),
            RMDestMen = max(RMDestMen),
            RMTransitGirls = max(RMTransitGirls),
            RMTransitBoys = max(RMTransitBoys),
            RMTransitWomen =max(RMTransitWomen),
            RMTransitMen = max(RMTransitMen),
            RMHCGirls = max(RMHCGirls),
            RMHCBoys = max(RMHCBoys),
            RMHCWomen = max(RMHCWomen),
            RMHCMen = max(RMHCMen),
            RMPendularGirls = max(RMPendularGirls),
            RMPendularBoys = max(RMPendularBoys),
            RMPendularWomen = max(RMPendularWomen),
            RMPendularMen = max(RMPendularMen),
            RMReturneesGirls = max(RMReturneesGirls),
            RMReturneesBoys = max(RMReturneesBoys),
            RMReturneesWomen = max(RMReturneesWomen),
            RMReturneesMen =max(RMReturneesMen),
            Consolidated_CVA_Beneficiaries = max(Consolidated_CVA_Beneficiaries)) |> 
  # Sum values to determine the totals
  dplyr::rowwise() |> 
  dplyr::mutate(Consolidated_RMindestination = sum(RMDestGirls, RMDestBoys, RMDestWomen, RMDestMen, na.rm = TRUE),
         Consolidated_RM_in_transit = sum(RMTransitGirls, RMTransitBoys, RMTransitWomen, RMTransitMen, na.rm = TRUE),
         Consolidated_Host_Community = sum(RMHCGirls, RMHCBoys, RMHCWomen, RMHCMen, na.rm = TRUE),
         Consolidated_RM_Pendulars = sum(RMPendularGirls, RMPendularBoys, RMPendularWomen, RMPendularMen, na.rm = TRUE),
         Consolidated_Colombian_Returnees = sum(RMReturneesGirls, RMReturneesBoys, RMReturneesWomen, RMReturneesMen, na.rm = TRUE),
         Consolidated_Girls = sum(RMDestGirls, RMTransitGirls, RMHCGirls, RMPendularGirls, RMReturneesGirls, na.rm = TRUE),
         Consolidated_Boys = sum(RMDestBoys, RMTransitBoys, RMHCBoys, RMPendularBoys, RMReturneesBoys, na.rm = TRUE),
         Consolidated_Women = sum(RMDestWomen, RMTransitWomen, RMHCWomen, RMPendularWomen, RMReturneesWomen, na.rm = TRUE),
         Consolidated_Men = sum(RMDestMen, RMTransitMen, RMHCMen, RMPendularMen, RMReturneesMen, na.rm = TRUE),
         Consolidated_Other_under_18 = 0,
         Consolidated_Other_above_18 = 0) |> 
  # Drop extra column of breakdown values and reorder to match original format
  dplyr::select(-(5:24)) |> 
  # Get final Monthly Consolidated figures for Intersector
  dplyr::mutate(Monthly_Consolidated = sum(Consolidated_RMindestination, Consolidated_RM_in_transit,
                                    Consolidated_Host_Community,Consolidated_RM_Pendulars,
                                    Consolidated_Colombian_Returnees, na.rm = TRUE)) |> 
  dplyr::ungroup()

  consmaxfinaladmin1 <- rbind(consallsectors, consmaxmerge)
  
  consmaxfinalcountry <- consmaxfinaladmin1  |> 
    dplyr::group_by(Country, Month, Subsector) |> 
    dplyr::summarise(Admin1 = "Country level",
              Monthly_Consolidated = sum(Monthly_Consolidated),
              Consolidated_RMindestination = sum(Consolidated_RMindestination),
              Consolidated_RM_in_transit = sum(Consolidated_RM_in_transit),
              Consolidated_Host_Community = sum(Consolidated_Host_Community),
              Consolidated_RM_Pendulars = sum(Consolidated_RM_Pendulars),
              Consolidated_Colombian_Returnees = sum(Consolidated_Colombian_Returnees),
              Consolidated_Girls = sum(Consolidated_Girls),
              Consolidated_Boys = sum(Consolidated_Boys),
              Consolidated_Women = sum(Consolidated_Women),
              Consolidated_Men = sum(Consolidated_Men),
              Consolidated_Other_under_18 = sum(Consolidated_Other_under_18),
              Consolidated_Other_above_18 = sum(Consolidated_Other_above_18),
              Consolidated_CVA_Beneficiaries = sum(Consolidated_CVA_Beneficiaries))

   consfinal <- rbind(consmaxfinaladmin1, consmaxfinalcountry)  
}
   
   if (totalmodel == "southernconemodel")
     {
     # Model 3: Mixed approach in 3 steps:
     # Max across Shelter, Food security, Humanitarian transport and WASH
     # Take Protection (General) data
     # Sum Other sectors mentionned: Integration, Multipurporse CBI, Health, Education
     
     # Step1: Get data Max across Food Security, Shelter, Humanitarian transport and WASH
     consCSstep1 <- consallsectors |> 
     dplyr::filter(Subsector %in% c("Shelter", "Humanitarian Transportation", "WASH", "Food Security")) |> 
     dplyr::left_join(dfproportions, by = c("Country", "Admin1", "Subsector")) |> 
     # Drop AGD Categories as they will be substituted in the final file
     dplyr::select(-Consolidated_Girls, 
            -Consolidated_Boys, 
            -Consolidated_Women, 
            -Consolidated_Men, 
            -Consolidated_Other_above_18, 
            -Consolidated_Other_under_18) |> 
     # get the breakdown of each age and gender categories by multiplying the pop type category by the proportions
     dplyr::rowwise() |> 
     dplyr::mutate(RMDestGirls = round(Consolidated_RMindestination * Dest_GIrls,0),
            RMDestBoys = round(Consolidated_RMindestination * Dest_Boys,0),
            RMDestWomen = round(Consolidated_RMindestination * Dest_Women,0),
            RMDestMen = round(Consolidated_RMindestination * Dest_Men,0),
            RMTransitGirls = round(Consolidated_RM_in_transit * Transit_GIrls,0),
            RMTransitBoys = round(Consolidated_RM_in_transit * Transit_Boys,0),
            RMTransitWomen = round(Consolidated_RM_in_transit * Transit_Women,0),
            RMTransitMen = round(Consolidated_RM_in_transit * Transit_Men,0),
            RMHCGirls = round(Consolidated_Host_Community * HC_Girls,0),
            RMHCBoys = round(Consolidated_Host_Community * HC_Boys,0),
            RMHCWomen = round(Consolidated_Host_Community * HC_Women,0),
            RMHCMen = round(Consolidated_Host_Community * HC_Men,0),
            RMPendularGirls = round(Consolidated_RM_Pendulars * Pendular_Girls,0),
            RMPendularBoys = round(Consolidated_RM_Pendulars * Pendular_Boys,0),
            RMPendularWomen = round(Consolidated_RM_Pendulars * Pendular_Women,0),
            RMPendularMen = round(Consolidated_RM_Pendulars * Pendular_Men,0),
            RMReturneesGirls = round(Consolidated_Colombian_Returnees*Returnees_Girls,0),
            RMReturneesBoys = round(Consolidated_Colombian_Returnees*Returnees_Boys,0),
            RMReturneesWomen = round(Consolidated_Colombian_Returnees*Returnees_Women,0),
            RMReturneesMen = round(Consolidated_Colombian_Returnees*Returnees_Men,0)) |> 
     dplyr::ungroup() |> 
     dplyr::select(-(5:10),-(12:35)) |> 
     dplyr::group_by(Country, Admin1, Month) |> 
     # Get MAX Values for each Age and Gender categories in each population type
     dplyr::summarise(Subsector = "Intersector",
               RMDestGirls = max(RMDestGirls),
               RMDestBoys = max(RMDestBoys),
               RMDestWomen = max(RMDestWomen),
               RMDestMen = max(RMDestMen),
               RMTransitGirls = max(RMTransitGirls),
               RMTransitBoys = max(RMTransitBoys),
               RMTransitWomen =max(RMTransitWomen),
               RMTransitMen = max(RMTransitMen),
               RMHCGirls = max(RMHCGirls),
               RMHCBoys = max(RMHCBoys),
               RMHCWomen = max(RMHCWomen),
               RMHCMen = max(RMHCMen),
               RMPendularGirls = max(RMPendularGirls),
               RMPendularBoys = max(RMPendularBoys),
               RMPendularWomen = max(RMPendularWomen),
               RMPendularMen = max(RMPendularMen),
               RMReturneesGirls = max(RMReturneesGirls),
               RMReturneesBoys = max(RMReturneesBoys),
               RMReturneesWomen = max(RMReturneesWomen),
               RMReturneesMen =max(RMReturneesMen),
               Consolidated_CVA_Beneficiaries = max(Consolidated_CVA_Beneficiaries)) |> 
     # Sum values to determine the totals
     dplyr::rowwise() |> 
     dplyr::mutate(Consolidated_RMindestination = sum(RMDestGirls, RMDestBoys, RMDestWomen, RMDestMen, na.rm = TRUE),
            Consolidated_RM_in_transit = sum(RMTransitGirls, RMTransitBoys, RMTransitWomen, RMTransitMen, na.rm = TRUE),
            Consolidated_Host_Community = sum(RMHCGirls, RMHCBoys, RMHCWomen, RMHCMen, na.rm = TRUE),
            Consolidated_RM_Pendulars = sum(RMPendularGirls, RMPendularBoys, RMPendularWomen, RMPendularMen, na.rm = TRUE),
            Consolidated_Colombian_Returnees = sum(RMReturneesGirls, RMReturneesBoys, RMReturneesWomen, RMReturneesMen, na.rm = TRUE),
            Consolidated_Girls = sum(RMDestGirls, RMTransitGirls, RMHCGirls, RMPendularGirls, RMReturneesGirls, na.rm = TRUE),
            Consolidated_Boys = sum(RMDestBoys, RMTransitBoys, RMHCBoys, RMPendularBoys, RMReturneesBoys, na.rm = TRUE),
            Consolidated_Women = sum(RMDestWomen, RMTransitWomen, RMHCWomen, RMPendularWomen, RMReturneesWomen, na.rm = TRUE),
            Consolidated_Men = sum(RMDestMen, RMTransitMen, RMHCMen, RMPendularMen, RMReturneesMen, na.rm = TRUE),
            Consolidated_Other_under_18 = 0,
            Consolidated_Other_above_18 = 0) |> 
     # Drop extra column of breakdown values and reorder to match original format
     dplyr::select(-(5:24)) |> 
     # Get final Monthly Consolidated figures for Intersector
     dplyr::mutate(Monthly_Consolidated = sum(Consolidated_RMindestination, Consolidated_RM_in_transit,
                                       Consolidated_Host_Community,Consolidated_RM_Pendulars,
                                       Consolidated_Colombian_Returnees, na.rm = TRUE)) |> 
     dplyr::ungroup()
   
   # Step 2: Protection (General) data
   consCSstep2 <- consallsectors |> 
     dplyr::filter(Subsector== "Protection (General)") |> 
     dplyr::group_by(Country, Admin1, Month) |> 
     dplyr::summarise(Subsector = "Intersector",
               Monthly_Consolidated = sum(Monthly_Consolidated),
               Consolidated_RMindestination = sum( Consolidated_RMindestination), 
               Consolidated_RM_in_transit = sum(Consolidated_RM_in_transit),
               Consolidated_Host_Community = sum(Consolidated_Host_Community),
               Consolidated_RM_Pendulars = sum(Consolidated_RM_Pendulars),
               Consolidated_Colombian_Returnees = sum(Consolidated_Colombian_Returnees),
               Consolidated_Girls = sum(Consolidated_Girls), 
               Consolidated_Boys = sum(Consolidated_Boys),
               Consolidated_Women = sum( Consolidated_Women),
               Consolidated_Men = sum(Consolidated_Men),
               Consolidated_Other_under_18 = sum(Consolidated_Other_under_18),
               Consolidated_Other_above_18 = sum(Consolidated_Other_above_18),
               Consolidated_CVA_Beneficiaries = sum(Consolidated_CVA_Beneficiaries))
   
   # Step 3: sum data for all the other sector: Integration, Multipurporse CBI, Health, Education
   consCSstep3 <- consallsectors |> 
     dplyr::filter(Subsector %in% c("Multipurpose Cash Assistance (MPC)", "Integration", "Health", "Education")) |> 
     dplyr::group_by(Country, Admin1, Month) |> 
     dplyr::summarise(Subsector = "Intersector",
               Monthly_Consolidated = sum(Monthly_Consolidated),
               Consolidated_RMindestination = sum( Consolidated_RMindestination), 
               Consolidated_RM_in_transit = sum(Consolidated_RM_in_transit),
               Consolidated_Host_Community = sum(Consolidated_Host_Community),
               Consolidated_RM_Pendulars = sum(Consolidated_RM_Pendulars),
               Consolidated_Colombian_Returnees = sum(Consolidated_Colombian_Returnees),
               Consolidated_Girls = sum(Consolidated_Girls), 
               Consolidated_Boys = sum(Consolidated_Boys),
               Consolidated_Women = sum( Consolidated_Women),
               Consolidated_Men = sum(Consolidated_Men),
               Consolidated_Other_under_18 = sum(Consolidated_Other_under_18),
               Consolidated_Other_above_18 = sum(Consolidated_Other_above_18),
               Consolidated_CVA_Beneficiaries = sum(Consolidated_CVA_Beneficiaries))
   # Merge the 3 separate steps in a single file and sum the beneficiaries for intersector at Admin1
   consCSadmin1 <- rbind(consCSstep1, consCSstep2, consCSstep3) |> 
     dplyr::group_by(Country, Admin1, Month) |> 
     dplyr::summarise(Subsector = "Intersector",
               Monthly_Consolidated = sum(Monthly_Consolidated),
               Consolidated_RMindestination = sum( Consolidated_RMindestination), 
               Consolidated_RM_in_transit = sum(Consolidated_RM_in_transit),
               Consolidated_Host_Community = sum(Consolidated_Host_Community),
               Consolidated_RM_Pendulars = sum(Consolidated_RM_Pendulars),
               Consolidated_Colombian_Returnees = sum(Consolidated_Colombian_Returnees),
               Consolidated_Girls = sum(Consolidated_Girls), 
               Consolidated_Boys = sum(Consolidated_Boys),
               Consolidated_Women = sum( Consolidated_Women),
               Consolidated_Men = sum(Consolidated_Men),
               Consolidated_Other_under_18 = sum(Consolidated_Other_under_18),
               Consolidated_Other_above_18 = sum(Consolidated_Other_above_18),
               Consolidated_CVA_Beneficiaries = sum(Consolidated_CVA_Beneficiaries))

   consCSAdminFull <- rbind(consCSadmin1, consallsectors)
   
  # Get country level figures
   consCScountry <- consCSAdminFull  |> 
     dplyr::group_by(Country, Month, Subsector) |> 
     dplyr::summarise(Admin1 = "Country level",
               Monthly_Consolidated = sum(Monthly_Consolidated),
               Consolidated_RMindestination = sum(Consolidated_RMindestination),
               Consolidated_RM_in_transit = sum(Consolidated_RM_in_transit),
               Consolidated_Host_Community = sum(Consolidated_Host_Community),
               Consolidated_RM_Pendulars = sum(Consolidated_RM_Pendulars),
               Consolidated_Colombian_Returnees = sum(Consolidated_Colombian_Returnees),
               Consolidated_Girls = sum(Consolidated_Girls),
               Consolidated_Boys = sum(Consolidated_Boys),
               Consolidated_Women = sum(Consolidated_Women),
               Consolidated_Men = sum(Consolidated_Men),
               Consolidated_Other_under_18 = sum(Consolidated_Other_under_18),
               Consolidated_Other_above_18 = sum(Consolidated_Other_above_18),
               Consolidated_CVA_Beneficiaries = sum(Consolidated_CVA_Beneficiaries))
   # Merge admin1 and country level figures final file
   consfinal <- rbind(consCSAdminFull, consCScountry)
}

##### Back to common consolidation process #############

  # Merge the tables before merging to template and final cleaning
   
   consfullmodel <- consfinal  |> 
     dplyr::full_join(finalmonthlytotal, by = c("Country", "Admin1", "Month", "Subsector"))

  # For countries with no admin1, filter out to only keep the "Country level" data
  # countrynoadmin1 <- c("Aruba", "Cura\u00e7ao", "Costa Rica", "Dominican Republic",
  #                      "Trinidad and Tobago", "Guyana", 
  #                    "Mexico", "Panama")
  # 
  #   if( is.null(countryname) ) {
  #     consfullmodel <- consfullmodel
  #   } else  {
  #     if (     countryname %in% countrynoadmin1){
  #     consfullmodel <- consfullmodel |> 
  #       dplyr::filter(Admin1 == "Country level") 
  #     } else { 
  #     consfullmodel <- consfullmodel}
  #    }

  # Merge with template
   consolidated_report <- dftemplate  |> 
     dplyr::full_join(consfullmodel, 
                      by = c("Country", "Admin1", "Month", "Subsector")) |> 
     dplyr::mutate_if(is.numeric,
                      ~replace(., is.na(.), 0))
   
  # Do the cumulative sum for the consolidated columns
   
   FinalConsolidated <- consolidated_report |> 
     dplyr::group_by(Country, Admin1, Subsector) |> 
     dplyr::arrange(Country, Admin1, Month) |> 
     dplyr::mutate('Consolidated Total' = cumsum(Monthly_Consolidated),
            'Consolidated In Destination' = cumsum(Consolidated_RMindestination),
            'Consolidated In Transit' = cumsum(Consolidated_RM_in_transit),
            'Consolidated Host Communities' = cumsum(Consolidated_Host_Community),
            'Consolidated Pendular' = cumsum(Consolidated_RM_Pendulars),
            'Consolidated Returnees' = cumsum(Consolidated_Colombian_Returnees),
            'Consolidated Girls' = cumsum(Consolidated_Girls),
            'Consolidated Boys' = cumsum(Consolidated_Boys),
            'Consolidated Women' = cumsum(Consolidated_Women),
            'Consolidated Men' = cumsum(Consolidated_Men),
            'Consolidated Other under 18' = cumsum(Consolidated_Other_under_18),
            'Consolidated Other above 18' = cumsum(Consolidated_Other_above_18),
            'Consolidated CVA Beneficiaries' = cumsum(Consolidated_CVA_Beneficiaries)) |> 
     dplyr::rowwise() |> 
     # Add 3 columns to check if the breakdowns are correct. 
     dplyr::mutate('Check PopType Breakdown' = ifelse(`Consolidated Total` == 0 | (`Consolidated Total` > 0 & 
                                                                              `Consolidated Total` == sum(`Consolidated In Destination`,
                                                                                                          `Consolidated In Transit`,
                                                                                                          `Consolidated Host Communities`,
                                                                                                          `Consolidated Pendular`,
                                                                                                          `Consolidated Returnees`,
                                                                                                          na.rm = TRUE)), "Ok", "Check Population Type breakdown"),
            'Check AGD Breakdown' = ifelse(`Consolidated Total` == 0 |
                                             (`Consolidated Total` > 0 & 
                                              `Consolidated Total`== sum(`Consolidated Girls`,
                                                                                                     `Consolidated Boys`,
                                                                                                     `Consolidated Women`,
                                                                                                     `Consolidated Men`,
                                                                                                     `Consolidated Other under 18`,
                                                                                                     `Consolidated Other above 18`,
                                                                                                     na.rm = TRUE)), "Ok", "Check AGD breakdown"),
            'Check CVA higher Total' = ifelse(`Consolidated CVA Beneficiaries` > `Consolidated Total`, "CVA Value higher than total", "ok")) |> 
     dplyr::ungroup() |> 
     dplyr::select(Platform,
            Country,
            Admin1,
            Month,
            Subsector,
            `Monthly Total Beneficiaries`,
            `Monthly CVA Beneficiaries`,
            `Consolidated Total`,
            `Consolidated In Destination`,
            `Consolidated In Transit`,
            `Consolidated Host Communities`,
            `Consolidated Pendular`,
            `Consolidated Returnees`,
            `Consolidated Girls`,
            `Consolidated Boys`,
            `Consolidated Women`,
            `Consolidated Men`,
            `Consolidated Other under 18`,
            `Consolidated Other above 18`,
            `Consolidated CVA Beneficiaries`,
            `Check PopType Breakdown`, 
            `Check AGD Breakdown`,
            `Check CVA higher Total`)
            
   return(FinalConsolidated)
    
}
```
  
```{r example-fct_aggregate_data}

lookup_dfindicator <- fct_read_lookup(type = "indicator")
df5W <- fct_read_data() 


df5Wctr <- fct_read_data(filter = "country",
                         value = "Bolivia")
resultpinsum <- fct_aggregate_data(df5W = df5Wctr,
                             lookup_dfindicator, 
                             proportions = "pin",  
                             totalmodel = "sum" )
## Check all 6 combinations...

### Combination 1
resultpinsum <- fct_aggregate_data(df5W,
                             lookup_dfindicator, 
                             proportions = "pin",  
                             totalmodel = "sum"   
)

head(resultpinsum, 10)

### Combination 2
resulttargetsum <- fct_aggregate_data(df5W,
                             lookup_dfindicator,
                             proportions = "target",  
                             totalmodel = "sum"   
)

head(resulttargetsum, 10)


### Combination 3
resultpinmaxsector <- fct_aggregate_data(df5W,
                             lookup_dfindicator,
                             proportions = "pin",  
                             totalmodel = "maxsector"   
)

head(resultpinmaxsector, 10)


### Combination 4
resulttargetmaxsector<- fct_aggregate_data(df5W,
                             lookup_dfindicator,
                             proportions = "target",  
                             totalmodel = "maxsector"   
)

head(resulttargetmaxsector, 10)


### Combination 5
resultpinsouthernconemodel <- fct_aggregate_data(df5W,
                             lookup_dfindicator,
                             proportions = "pin",  
                             totalmodel = "southernconemodel"   
)

head(resultpinsouthernconemodel, 10)


### Combination 6
resulttargetsouthernconemodel <- fct_aggregate_data(df5W,
                             lookup_dfindicator,
                             proportions = "target", 
                             totalmodel = "southernconemodel"   
)

head(resulttargetsouthernconemodel, 10)




```
  
```{r tests-fct_aggregate_data}
test_that("fct_aggregate_data works", {
  expect_true(inherits(fct_aggregate_data, "function")) 
})
```
  
  

# run_app


<!--
Create a chunk for the core of the function

- The chunk needs to be named `function` at least
- It contains the code of a documented function
- The chunk can also be named `function-my_function` to make it easily
findable in your Rmd
- Let the `@examples` part empty, and use the next `examples` chunk instead to present reproducible examples

After inflating the template

-  This function code will automatically be added in a new file in the "R/" directory
-->
    
```{r function-run_app}
#' Run the Shiny Application
#'
#' @param ... arguments to pass to golem_opts.
#' See `?golem::get_golem_options` for more details.
#' @inheritParams shiny::shinyApp
#'
#' @export
#' @importFrom shiny shinyApp
#' @importFrom golem with_golem_options
#
run_app <- function(
    onStart = NULL,
    options = list(),
    enableBookmarking = NULL,
    uiPattern = "/",
    ...
) {
  with_golem_options(
    app = shinyApp(
      ui = app_ui,
      server = app_server,
      onStart = onStart,
      options = options,
      enableBookmarking = enableBookmarking,
      uiPattern = uiPattern
    ),
    golem_opts = list(...)
  )
}

```

<!--
Create a chunk with an example of use for your function

- The chunk needs to be named `examples` at least
- It contains working examples of your function
- The chunk is better be named `examples-my_median` to be handled
correctly when inflated as a vignette

After inflating the template

-  This example will automatically be added in the '@examples' part of our function above in the "R/" directory
- This example will automatically be added in the vignette created from this Rmd template
-->

```{r example-run_app}
# run_app()
```



```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/function_documentation.Rmd", vignette_name = "Development")
```

