# WARNING - Generated by {fusen} from /dev/function_documentation.Rmd: do not edit by hand

#' fct_error_report
#' 
#' The functions perform systematic Data Quality Check 
#' 
#' Currently this includes the 19 following Check: 
#' 
#'  __Completeness__:
#' 
#'  1. missingcountry: Country and admin 1 information is missing.
#'  2. countryadmincheck: Administrative unit level 1 not matching the name in the ActivityInfo 5W "admin2" reference table.
#'  3.  admin1and2check: Administrative unit level 2 not matching the name for each respective admin1 in the ActivityInfo 5W "admin2" reference table. 
#'  4.  miss_appeal_org: Missing appealing organization or organization name not corresponding to the name included in the ActivityInfo 5W "partners" reference table
#'  5.  miss_setup: Checks if the field is empty, as it is mandatory to fill this variable with a "yes" for cases where there is an implementing partner, or with a "no" if the activity corresponds to direct implementation.
#'  6.  miss_implementing_org: If "yes" is selected in the "implementation set up" field, then a name for the implementing organization should be included in the corresponding field, otherwise it will retrieve an error.
#'  7.  miss_month: Missing month information.
#'  8.  missing_what: If there is missing information for the 5W "what" fields, more specifically: indicator sector, indicator, activity name, RMRP activity, and CVA.
#'   
#'  __Consistency__:
#'  9.  wrongsectindicator: If the indicator name does not correspond to the selected sector, as per the ActivityInfo 5W "indicators RMRP 23" reference table. 
#'  10.  zeroCVA: when the CVA field is "yes", then a CVA value in USD must be entered, otherwise it will retrieve an error.
#'  11.  missingmechanism: when the CVA field is "yes", then a CVA delivery mechanism must be entered, otherwise it will retrieve an error.
#'  12.  CVANotoYes: If the CVA = “No” but that the Value or Delivery Mechanism contains data, it will retrieve an error as those should be empty or the CVA should be “Yes”.          
#'  13.  MultipurposeSector: It will retrieve an error when the selected indicator sector is "Multipurpose Cash Assistance (MPC)" and CVA = "No". 
#'  14.  DirectAssistanceNoBenef: If the indicator type selected is "Direct Assistance" then there should be positive values entered for new monthly beneficiaries and total beneficiaries, otherwise it will retrieve an error.  
#'  15.  NewBenefvstotal: if the value for new monthly beneficiaries exceeds the value of total monthly beneficiaries. 
#'  
#'  __Accuracy__:
#'  16.  PopTypeBreakdown:  For "Direct Assistance" indicators, checks if the sum of the population type breakdown equals the new beneficiaries value. If an ERROR appears, please review the breakdown values or the new beneficiaries' values in the corresponding activity
#'  17.  AGDBreakdown: For "Direct Assistance" indicators, checks if the sum of the age and gender breakdown equals the new beneficiaries' value. If an ERROR appears, please review the breakdown values or the new beneficiaries' values in the corresponding activity
#'  18.  CBuildingNoBenef: For "Capacity Building" indicators, checks if there is positive values for the total monthly beneficiaries field, as this field should be reported, otherwise it will retrieve an error.
#'  19.  NoOutput: For indicators other than the ones included under "Direct Assistance" and "Capacity Building", a value for"Quantity of Output" should always be reported, otherwise it will retrieve an error.
#' 
#' 
#' @param df5W fame with response tracking data
#' @param lookup_dfindicator fame with indicator look up 
#' @param lookup_dfadmin1 fame with admin1 look up 
#' @param lookup_dfadmin2 fame with admin2 look up 
#' @param lookup_dfpartner fame with partner look up 
#' 
#' @import ggplot2 
#' @importFrom scales label_number cut_short_scale
#' @importFrom unhcrthemes theme_unhcr
#' @importFrom dplyr arrange mutate  left_join select ungroup 
#'                    rowwise row_number
#'                    
#' @importFrom purrr discard
#' 
#' @return result list with results and data error...
#' 
#' @export
#' @examples
#' lookup_dfadmin1 <- fct_read_lookup(type = "admin1")
#' lookup_dfadmin2 <- fct_read_lookup(type = "admin2")
#' lookup_dfpartner <- fct_read_lookup(type = "partner")
#' 
#' lookup_dfindicator <- fct_read_lookup(type = "indicator")
#' 
#' df5Wpart <- fct_read_data(filter = "partner",
#'     value = "United Nations High Commissioner for Refugees (UNHCR)")
#' resultpart <- fct_error_report(df5Wpart, 
#'                                lookup_dfadmin1, 
#'                                lookup_dfadmin2, 
#'                                lookup_dfindicator, 
#'                                lookup_dfpartner)
#'  
#' print(resultpart$plot_Country)
#' 
#' ## Second example
#' df5Wctr <- fct_read_data(filter = "country",
#'                          value = "Peru")
#' resultctr <- fct_error_report(df5Wctr, 
#'                                lookup_dfadmin1, 
#'                                lookup_dfadmin2, 
#'                                lookup_dfindicator, 
#'                                lookup_dfpartner)
#' 
#' print(resultctr$plot_Appealing) 
#' 
#' ## Display fixed data 
#' head(resultctr[["ErrorReportclean"]], 10)
#' 
#' 
fct_error_report <- function(  df5W, 
                               lookup_dfadmin1, 
                               lookup_dfadmin2, 
                               lookup_dfindicator, 
                               lookup_dfpartner ){
  
  # Data wrangling of reference table for quality check
  # Vectors for verification
  partnerlist <- unique(as.vector(lookup_dfpartner["Name"]))
  countrylist <- unique(as.vector(lookup_dfadmin1["countryadmin1"]))
  admin2list <- unique(as.vector(lookup_dfadmin2["admin1and2"]))
  sectindiclist <-  as.vector(lookup_dfindicator["sectindic"])
  
  # concatenate relevant columns to then check if cascading values are matching, 
  df5Werror <- df5W  |>
    dplyr::mutate(
      countryadmin1 = paste(Country, Admin1),
      Admin1and2 = paste(Admin1, Admin2),
      sectorindicator = paste(Subsector, Indicator)) |>
    dplyr::left_join(lookup_dfindicator, by = c("Subsector", "Indicator")) |>
    dplyr::select(-CODE, -sectindic)
    
  # Data Quality Check #############
  df5Werror <- df5Werror  |>
    dplyr::rowwise() |>
    # Where: check missing mandatory fields, 
    # Country-Admin1 pairs and Admin1-Admin2 pairs
    dplyr::mutate(
      missingcountry = ifelse(is.na(Country) | is.na(Admin1), 1,  NA),
      countryadmincheck = ifelse(!any(countryadmin1 == countrylist[[1]]), 1,  NA),
      admin1and2check = ifelse(!is.na(Admin2) & !any(Admin1and2 == admin2list[[1]]), 1,  NA),
    # Who: Missing values and Org names that are not part of the list
      miss_appeal_org = ifelse(!is.na(Appealing_org) & any(Appealing_org == partnerlist[[1]]),  NA, 1),
      miss_setup = ifelse(is.na(Implementation), 1,  NA),
      miss_implementing_org = ifelse((Implementation == "Yes" & 
                                        (is.na(Implementing_partner) | !any(Implementing_partner == partnerlist[[1]]))) | 
                                       (Implementation == "No" & !is.na(Implementing_partner)), 1,  NA),
      # When: Missing month
      miss_month = ifelse(is.na(Month), 1,  NA),
      # What: missing values and inconsistencies in CVA
      missing_what = ifelse(is.na(Subsector)|is.na(Indicator)|is.na(Activity_Name)| is.na(RMRPActivity)|is.na(CVA), 1,  NA),
      wrongsectindicator = ifelse(!any(sectorindicator == sectindiclist[[1]]), 1,  NA),
      # CVA mistakes
      zeroCVA = ifelse(CVA == "Yes" & (is.na(Value)|  Value == 0), 1,  NA),
      missingmechanism = ifelse(CVA == "Yes" & is.na(Delivery_mechanism), 1,  NA),
      CVANotoYes = ifelse((!is.na(Delivery_mechanism) | (!is.na(Value) & Value > 0)) & CVA == "No", 1,  NA),
      MultipurposeSector = ifelse(Subsector == "Multipurpose Cash Assistance (MPC)" & CVA == "No", 1,  NA),
      # Output and Breakdown related mistakes. Reviews will be divided according to indicator types
      # PNiN indicator related mistakes
      DirectAssistanceNoBenef = ifelse(IndicatorType == 'Direct Assistance' &
                                         ((is.na(New_beneficiaries) | New_beneficiaries == 0) &
                                            (is.na(Total_monthly) | Total_monthly == 0)), 1,  NA),
      NewBenefvstotal = ifelse(IndicatorType == 'Direct Assistance' & New_beneficiaries > Total_monthly, 1,  NA),
      PopTypeBreakdown = ifelse(IndicatorType == 'Direct Assistance' & New_beneficiaries != sum(IN_DESTINATION,
                                                                                   IN_TRANSIT,
                                                                                   Host_Communities,
                                                                                   PENDULARS,
                                                                                   Returnees, na.rm = TRUE), 1,  NA),
      AGDBreakdown = ifelse(IndicatorType == 'Direct Assistance' & New_beneficiaries != sum(Girls,
                                                                                Boys,
                                                                                Women,
                                                                                Men,
                                                                              Other_under,
                                                                                Other_above, na.rm = TRUE), 1,  NA),
      # Capacity Building indicators
      CBuildingNoBenef = ifelse(IndicatorType == 'Capacity Building' &
                                  (Total_monthly == 0 | is.na(Total_monthly)),
                                1,  NA),
      # Todos los otros indicadores
      NoOutput = ifelse ((IndicatorType != 'Capacity Building' &
                            IndicatorType != 'Direct Assistance') & 
                           (Quantity_output == 0 | is.na(Quantity_output)), 
                         1,  NA)   ) |>
    ## Compile all errors 
    dplyr::mutate( QA = sum( 
      c( missingcountry, countryadmincheck, admin1and2check, miss_appeal_org,
         miss_setup, miss_implementing_org, miss_month, missing_what, 
         wrongsectindicator, zeroCVA, missingmechanism, CVANotoYes,
         MultipurposeSector, DirectAssistanceNoBenef, NewBenefvstotal, 
         PopTypeBreakdown, AGDBreakdown, CBuildingNoBenef, NoOutput) , 
      na.rm = TRUE) ,
       Review = ifelse (QA > 0, "Please review activity", "OK") ,
       Review2 = ifelse (QA > 0, 1, NA) ) |>
    
    dplyr::ungroup() |> 
    ## Remove empty column
    purrr::discard(~all(is.na(.) | . ==""))
  
   # table( df5Werror$QA, useNA = "ifany")
   # table( df5Werror$Review, useNA = "ifany")
   #table( df5Werror$Review2, useNA = "ifany")
   ## Add to result
  
 
  ## Add summary plot 
   
   
  # df5Werror |> 
  #   dplyr::select(Appealing_org, Review ) |>
  #   dply::group_by(Appealing_org) |>
  #   dplyr::summarise(Review = dplyr:: )
  # pivot_longer(cols = -Year) |>
  # ggplot() +
  # geom_col(aes(x = Year, y = value, fill = name),
  #          width = 0.7,
  #          position = position_fill()) +
  # unhcrthemes::scale_fill_unhcr_d(palette = "pal_unhcr") +
  # scale_y_continuous(expand = expansion(c(0, 0.01)),
  #                    labels = percent) +
  # labs(title = "Levels of earmarking | 2012-2020",
  #      caption = paste0( "Source:R4V | Data as of ",format(Sys.Date(),  '%d %B %Y'))   ) +
  # unhcrthemes::theme_unhcr(font_size = 14,
  #             grid = "Y",
  #             axis = "x",
  #             axis_title = FALSE)
   
   require(ggplot2)
  plot_Appealing <- df5Werror |>
        dplyr::select(Appealing_org, Review2 ) |>
        dplyr::group_by(Appealing_org) |>
        dplyr::summarise(Review2 = sum(Review2, na.rm = TRUE) ) |>
       dplyr::filter(Review2  >0 )|>
	      #filter(!is.na(Review)) |>
	      ggplot2::ggplot() +
	      aes(x = reorder(Appealing_org, Review2),
	          y = Review2) +
	      geom_col(fill = "#0c4c8a" ) +
       # scale_y_continuous(expand = expansion(c(0, 0.1)),
       #               labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
	      coord_flip()  +
        labs(
            title =  "Number of Activity to review by Appealing Org.",
            subtitle = "Data Quality Review",
            x = "",
            y = "",
            caption = paste0( "Source:R4V | Data as of ",format(Sys.Date(),  '%d %B %Y'))    ) +
        unhcrthemes::theme_unhcr(font_size = 14,
                      grid = "X",
                      rel_small = 6/9#,
                     # axis = "y",
                      #axis_title = TRUE,
                     # legend = FALSE,
                     # axis_text = "y"
                    )
  
  
   ## Second plot 
  plot_Country <-  df5Werror |>
        dplyr::select(Country, Review2 ) |>
        dplyr::group_by(Country) |>
        dplyr::summarise(Review2 = sum(Review2, na.rm = TRUE) ) |>
       dplyr::filter(Review2  >0 )|>
	      ggplot() +
	      aes(x =  reorder(Country, Review2) , 
	          y = Review2) +
	      geom_col(fill = "#0c4c8a") +
       # scale_y_continuous(expand = expansion(c(0, 0.1)),
       #               labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
	      coord_flip()  +
        labs(
            title =  "Number of Activity to review by Country",
            subtitle = "Data Quality Review",
            x = "",
            y = "",
            caption = paste0( "Source: R4V | Data as of ",
             format(Sys.Date(),  '%d %B %Y'))    ) +
        unhcrthemes::theme_unhcr(font_size = 14,
                      grid = "X",
                      rel_small = 6/9#,
                     # axis = "y",
                      #axis_title = TRUE,
                     # legend = FALSE,
                     # axis_text = "y"
                    )
   result <- list (
               ErrorReportclean = df5Werror, 
               plot_Country = plot_Country,
               plot_Appealing = plot_Appealing)

  return(result)
    
}
