# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' fct_read_lookup
#' 
#' Pull Data From ActivityInfo
#' 
#' Note that this function is specific to a specific DB schema -
#' the form to query as well as the columns variable name are hard coded and 
#' would need to be adjusted if the DB change
#' 
#' Note also that the function is based on a token stored as an environment 
#' variable
#' 
#'  # Credentials set up as environment variables - 
#'  
#'  # token <- "activityinfotoken.."
#'  # print(Sys.setenv(ACTIVITYINFOTOKEN = token))   
#'  # Sys.getenv("ACTIVITYINFOTOKEN")
#'  # rm(token)
#'  
#' @param type of one 
#'                * dfadmin1  
#'                * dfadmin2  
#'                * dfindicator   
#'                * dfpartner  
#' 
#' @return frame with the content of the activity info DB 
#' 
#' 
#' @importFrom activityinfo activityInfoToken queryTable
#' @importFrom dplyr  arrange mutate_at rowwise ungroup
#' 
#' @export
#' @examples
#' lookup_dfadmin1 <- fct_read_lookup(type = "admin1")
#' head(lookup_dfadmin1, 10)
#'
#' lookup_dfadmin2 <- fct_read_lookup(type = "admin2")
#' head(lookup_dfadmin2, 10)
#'
#' lookup_dfindicator <- fct_read_lookup(type = "indicator")
#' head(lookup_dfindicator, 10)
#'
#' lookup_dfpartner <- fct_read_lookup(type = "partner")
#' head(lookup_dfpartner, 10)
#'
fct_read_lookup <- function(type ){

  activityinfo::activityInfoToken(Sys.getenv("ACTIVITYINFOTOKEN"),
                                prompt = FALSE)

  # Not recommended but if needed, chose to write the 5W as a xlsx file in repository
  # Get other reference table used during the data quality check
  # Loaded from AI regardless the method for 5W used
  if( type == "admin1") {
  lookup  <- activityinfo::queryTable(
    form= "cryi2v5lo79a2dh9", #fix it 
                           "Country" = "c8u26b8kxeqpy0k4",
                           "Admin1" = "c3ns3zikxeqq4h95",
                           "ISOCode" = "cl3sspjkxeqq8yq6",
    truncateStrings = FALSE) |> 
    dplyr::rowwise() |> 
    dplyr::mutate(countryadmin1 = paste(Country, Admin1)) |> 
    dplyr::ungroup()
  }
  
  if( type == "admin2") {
  lookup <- activityinfo::queryTable(
    form= "cbxcifmlo79a2de3",  #fix it 
                         "Country" = "cnkb6jykxgdeemm4r.c8u26b8kxeqpy0k4",
                         "Admin1" = "cnkb6jykxgdeemm4r.c3ns3zikxeqq4h95",
                         "Admin2" = "cs2esadkx6hkt7j6", 
    truncateStrings = FALSE) |> 
    dplyr::rowwise() |> 
    dplyr::mutate(admin1and2 = paste(Admin1, Admin2)) |> 
    dplyr::ungroup()
  }
  
  if( type == "indicator") {
  lookup  <- activityinfo::queryTable(
    form= "cv2dgf6lo79a2de6",  #fix it 
                              "CODE" = "cdhugiblctco28h3",
                              "Subsector" = "cagw22hlctcp2vu5",
                              "Indicator" = "c1oo0eclctcqtjp8",
                              "IndicatorType" = "cuskmf7lctcszoga", 
    truncateStrings = FALSE) |> 
    dplyr::rowwise() |> 
    dplyr::mutate(sectindic = paste(Subsector, Indicator)) |> 
    dplyr::ungroup()
  }
  
  if( type == "partner") {
  lookup <- activityinfo::queryTable(
    form= "cwt6nqqlo79a2de7", #fix it
                          "AOIDORG" = "cnhvpo4kumvyqla8",
                          "Name" = "ckj5zamkumvyysv9",
                          "Type" = "c813krekumw0449j",
                          "RMlead" = "cu2zbr0l1z3adte7", 
                          truncateStrings = FALSE)
  
  }

   return(lookup)
    
}
