# remotes::install_github("thinkr-open/checkhelper")
# checkhelper::print_globals()

globalVariables(unique(c(
  # fct_aggregate_data: 
  "Admin1", "Boys", "Check AGD Breakdown", "Check CVA higher Total", "Check PopType Breakdown", "CODE", "Consolidated Boys", "Consolidated CVA Beneficiaries", "Consolidated Girls", "Consolidated Host Communities", "Consolidated In Destination", "Consolidated In Transit", "Consolidated Men", "Consolidated Other above 18", "Consolidated Other under 18", "Consolidated Pendular", "Consolidated Returnees", "Consolidated Total", "Consolidated Women", "Consolidated_Boys", "Consolidated_Colombian_Returnees", "Consolidated_CVA_Beneficiaries", "Consolidated_Girls", "Consolidated_Host_Community", "Consolidated_Men", "Consolidated_Other_above_18", "Consolidated_Other_under_18", "Consolidated_RM_in_transit", "Consolidated_RM_Pendulars", "Consolidated_RMindestination", "Consolidated_Women", "Country", "CVA", "Dest_Boys", "Dest_GIrls", "Dest_Men", "Dest_Women", "df5Wconsolidated", "Girls", "HC_Boys", "HC_Girls", "HC_Men", "HC_Women", "Host_Communities", "IN_DESTINATION", "IN_TRANSIT", "IndicatorType", "Men", "Month", "Monthly CVA Beneficiaries", "Monthly Total Beneficiaries", "Monthly_Consolidated", "New_beneficiaries", "Other_above", "Other_under", "Pendular_Boys", "Pendular_Girls", "Pendular_Men", "Pendular_Women", "PENDULARS", "Platform", "Returnees", "Returnees_Boys", "Returnees_Girls", "Returnees_Men", "Returnees_Women", "RMDestBoys", "RMDestGirls", "RMDestMen", "RMDestWomen", "RMHCBoys", "RMHCGirls", "RMHCMen", "RMHCWomen", "RMPendularBoys", "RMPendularGirls", "RMPendularMen", "RMPendularWomen", "RMReturneesBoys", "RMReturneesGirls", "RMReturneesMen", "RMReturneesWomen", "RMTransitBoys", "RMTransitGirls", "RMTransitMen", "RMTransitWomen", "sectindic", "Subsector", "Total_monthly", "Transit_Boys", "Transit_GIrls", "Transit_Men", "Transit_Women", "Women", 
  # fct_error_report: 
  "Activity_Name", "Admin1", "Admin1and2", "admin1and2check", "Admin2", "AGDBreakdown", "Appealing_org", "Boys", "CBuildingNoBenef", "CampaignWithPopulationType","CampaignWithAgeAndGender", "CapacityBuildingWithPopulationType", "ActivityWithBeneficiariesRegistered", "CODE", "Country", "countryadmin1", "countryadmincheck", "CVA", "CVANotoYes", "Delivery_mechanism", "DirectAssistanceNoBenef", "DirectAssistanceWithQuantityOfOutput", "Girls", "Host_Communities", "Implementation", "Implementing_partner", "IN_DESTINATION", "IN_TRANSIT", "Indicator", "IndicatorType", "Men", "miss_appeal_org", "miss_implementing_org", "miss_month", "miss_setup", "missing_what", "missingcountry", "missingmechanism", "Month", "MultipurposeSector", "New_beneficiaries", "NewBenefvstotal", "NoOutput", "Other_above", "Other_under", "PENDULARS", "PopTypeBreakdown", "QA", "Quantity_output", "Returnees", "Review2", "RMRPActivity", "sectindic", "sectorindicator", "Subsector", "Total_monthly", "Value", "Women", "wrongsectindicator", "zeroCVA", 
  # fct_read_data: 
  "Admin1", "Admin2", "Country", "dfadmin1", "dfadmin2", "dfindicator", "dfpartner", "Indicator", "Month", "Subsector", 
  # mod_read_data_server: 
  "Boys", "Country", "Girls", "Host_Communities", "IN_DESTINATION", "IN_TRANSIT", "Men", "Month", "New_beneficiaries", "Other_above", "Other_under", "PENDULARS", "Quantity_output", "Returnees", "Total_monthly", "Value", "Women"
)))